# Run for main or PRs against main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PSRule analysis
        uses: Microsoft/ps-rule@v2
        with:
          modules: "PSRule.Rules.Azure"
          inputType: repository
